services:
  auth-service:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./Auth/
          target: /usr/src/app/
          action: sync
        - path: ./Auth/package.json
          action: rebuild
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=8081
      - JWT_SECRET=123soleil
      - MONGO_URI=mongodb://root:example@database:27017/micro?authSource=admin
      
  product-service:
    build:
      context: ./Product
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./Product/
          target: /usr/src/app/
          action: sync
        - path: ./Product/package.json
          action: rebuild
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=8082
      - JWT_SECRET=123soleil
      - MONGO_URI=mongodb://root:example@database:27017/micro?authSource=admin

  api-gateway:
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
    networks:
      - app-network
    develop:
      watch:
        - path: ./API_Gateway/
          target: /usr/src/app/
          action: sync
        - path: ./API_Gateway/package.json
          action: rebuild
    environment:
      - JWT_SECRET=123soleil

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
